/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class IWPEnum.
* @enum {}
* @readonly
*/
export default class IWPEnum {
    
        /**
         * value: "PREMIUM"
         * @const
         */
        "PREMIUM" = "PREMIUM";

    
        /**
         * value: "INTERIM_PROFESSIONAL"
         * @const
         */
        "INTERIM_PROFESSIONAL" = "INTERIM_PROFESSIONAL";

    
        /**
         * value: "PROFESSIONAL"
         * @const
         */
        "PROFESSIONAL" = "PROFESSIONAL";

    
        /**
         * value: "SPEAKER_ID"
         * @const
         */
        "SPEAKER_ID" = "SPEAKER_ID";

    
        /**
         * value: "FINAL"
         * @const
         */
        "FINAL" = "FINAL";

    
        /**
         * value: "MECHANICAL"
         * @const
         */
        "MECHANICAL" = "MECHANICAL";

    
        /**
         * value: "CUSTOMER_APPROVED_RETURN"
         * @const
         */
        "CUSTOMER_APPROVED_RETURN" = "CUSTOMER_APPROVED_RETURN";

    
        /**
         * value: "CUSTOMER_APPROVED_TRANSLATION"
         * @const
         */
        "CUSTOMER_APPROVED_TRANSLATION" = "CUSTOMER_APPROVED_TRANSLATION";

    

    /**
    * Returns a <code>IWPEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/IWPEnum} The enum <code>IWPEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

