/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobOptions from './JobOptions';

/**
 * The JobInfoResponse model module.
 * @module model/JobInfoResponse
 * @version 1.0.0
 */
class JobInfoResponse {
    /**
     * Constructs a new <code>JobInfoResponse</code>.
     * @alias module:model/JobInfoResponse
     */
    constructor() { 
        
        JobInfoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobInfoResponse} obj Optional instance to populate.
     * @return {module:model/JobInfoResponse} The populated <code>JobInfoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobInfoResponse();

            if (data.hasOwnProperty('JobId')) {
                obj['JobId'] = ApiClient.convertToType(data['JobId'], 'String');
            }
            if (data.hasOwnProperty('JobName')) {
                obj['JobName'] = ApiClient.convertToType(data['JobName'], 'String');
            }
            if (data.hasOwnProperty('MediaLengthSeconds')) {
                obj['MediaLengthSeconds'] = ApiClient.convertToType(data['MediaLengthSeconds'], 'Number');
            }
            if (data.hasOwnProperty('ExternalId')) {
                obj['ExternalId'] = ApiClient.convertToType(data['ExternalId'], 'String');
            }
            if (data.hasOwnProperty('Priority')) {
                obj['Priority'] = ApiClient.convertToType(data['Priority'], 'String');
            }
            if (data.hasOwnProperty('Fidelity')) {
                obj['Fidelity'] = ApiClient.convertToType(data['Fidelity'], 'String');
            }
            if (data.hasOwnProperty('JobStatus')) {
                obj['JobStatus'] = ApiClient.convertToType(data['JobStatus'], 'String');
            }
            if (data.hasOwnProperty('Options')) {
                obj['Options'] = JobOptions.constructFromObject(data['Options']);
            }
            if (data.hasOwnProperty('ReturnTargets')) {
                obj['ReturnTargets'] = ApiClient.convertToType(data['ReturnTargets'], Object);
            }
            if (data.hasOwnProperty('SourceLanguage')) {
                obj['SourceLanguage'] = ApiClient.convertToType(data['SourceLanguage'], 'String');
            }
            if (data.hasOwnProperty('TargetLanguage')) {
                obj['TargetLanguage'] = ApiClient.convertToType(data['TargetLanguage'], 'String');
            }
            if (data.hasOwnProperty('CreationDate')) {
                obj['CreationDate'] = ApiClient.convertToType(data['CreationDate'], 'String');
            }
            if (data.hasOwnProperty('StartDate')) {
                obj['StartDate'] = ApiClient.convertToType(data['StartDate'], 'String');
            }
            if (data.hasOwnProperty('DueDate')) {
                obj['DueDate'] = ApiClient.convertToType(data['DueDate'], 'String');
            }
            if (data.hasOwnProperty('CompletedDate')) {
                obj['CompletedDate'] = ApiClient.convertToType(data['CompletedDate'], 'String');
            }
            if (data.hasOwnProperty('ReturnDate')) {
                obj['ReturnDate'] = ApiClient.convertToType(data['ReturnDate'], 'String');
            }
            if (data.hasOwnProperty('AuthorizationDate')) {
                obj['AuthorizationDate'] = ApiClient.convertToType(data['AuthorizationDate'], 'String');
            }
            if (data.hasOwnProperty('JobDifficulty')) {
                obj['JobDifficulty'] = ApiClient.convertToType(data['JobDifficulty'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} JobId
 */
JobInfoResponse.prototype['JobId'] = undefined;

/**
 * @member {String} JobName
 */
JobInfoResponse.prototype['JobName'] = undefined;

/**
 * @member {Number} MediaLengthSeconds
 */
JobInfoResponse.prototype['MediaLengthSeconds'] = undefined;

/**
 * Depends on third-party integrations.
 * @member {String} ExternalId
 */
JobInfoResponse.prototype['ExternalId'] = undefined;

/**
 * @member {module:model/JobInfoResponse.PriorityEnum} Priority
 */
JobInfoResponse.prototype['Priority'] = undefined;

/**
 * @member {module:model/JobInfoResponse.FidelityEnum} Fidelity
 */
JobInfoResponse.prototype['Fidelity'] = undefined;

/**
 * @member {module:model/JobInfoResponse.JobStatusEnum} JobStatus
 */
JobInfoResponse.prototype['JobStatus'] = undefined;

/**
 * @member {module:model/JobOptions} Options
 */
JobInfoResponse.prototype['Options'] = undefined;

/**
 * @member {Object} ReturnTargets
 */
JobInfoResponse.prototype['ReturnTargets'] = undefined;

/**
 * RFC 5646 Language Code
 * @member {String} SourceLanguage
 */
JobInfoResponse.prototype['SourceLanguage'] = undefined;

/**
 * RFC 5646 Language Code
 * @member {String} TargetLanguage
 */
JobInfoResponse.prototype['TargetLanguage'] = undefined;

/**
 * ISO 8601 Date String
 * @member {String} CreationDate
 */
JobInfoResponse.prototype['CreationDate'] = undefined;

/**
 * ISO 8601 Date String
 * @member {String} StartDate
 */
JobInfoResponse.prototype['StartDate'] = undefined;

/**
 * ISO 8601 Date String
 * @member {String} DueDate
 */
JobInfoResponse.prototype['DueDate'] = undefined;

/**
 * ISO 8601 Date String
 * @member {String} CompletedDate
 */
JobInfoResponse.prototype['CompletedDate'] = undefined;

/**
 * ISO 8601 Date String
 * @member {String} ReturnDate
 */
JobInfoResponse.prototype['ReturnDate'] = undefined;

/**
 * ISO 8601 Date String
 * @member {String} AuthorizationDate
 */
JobInfoResponse.prototype['AuthorizationDate'] = undefined;

/**
 * @member {module:model/JobInfoResponse.JobDifficultyEnum} JobDifficulty
 */
JobInfoResponse.prototype['JobDifficulty'] = undefined;





/**
 * Allowed values for the <code>Priority</code> property.
 * @enum {String}
 * @readonly
 */
JobInfoResponse['PriorityEnum'] = {

    /**
     * value: "STANDARD"
     * @const
     */
    "STANDARD": "STANDARD",

    /**
     * value: "PRIORITY"
     * @const
     */
    "PRIORITY": "PRIORITY"
};


/**
 * Allowed values for the <code>Fidelity</code> property.
 * @enum {String}
 * @readonly
 */
JobInfoResponse['FidelityEnum'] = {

    /**
     * value: "MECHANICAL"
     * @const
     */
    "MECHANICAL": "MECHANICAL",

    /**
     * value: "PREMIUM"
     * @const
     */
    "PREMIUM": "PREMIUM",

    /**
     * value: "PROFESSIONAL"
     * @const
     */
    "PROFESSIONAL": "PROFESSIONAL"
};


/**
 * Allowed values for the <code>JobStatus</code> property.
 * @enum {String}
 * @readonly
 */
JobInfoResponse['JobStatusEnum'] = {

    /**
     * value: "Authorizing"
     * @const
     */
    "Authorizing": "Authorizing",

    /**
     * value: "Pending"
     * @const
     */
    "Pending": "Pending",

    /**
     * value: "In Process"
     * @const
     */
    "In Process": "In Process",

    /**
     * value: "Complete"
     * @const
     */
    "Complete": "Complete",

    /**
     * value: "Media Failure"
     * @const
     */
    "Media Failure": "Media Failure",

    /**
     * value: "Reviewing"
     * @const
     */
    "Reviewing": "Reviewing"
};


/**
 * Allowed values for the <code>JobDifficulty</code> property.
 * @enum {String}
 * @readonly
 */
JobInfoResponse['JobDifficultyEnum'] = {

    /**
     * value: "Good"
     * @const
     */
    "Good": "Good",

    /**
     * value: "Bad"
     * @const
     */
    "Bad": "Bad",

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown"
};



export default JobInfoResponse;

