/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PerformTranslationResponse model module.
 * @module model/PerformTranslationResponse
 * @version 1.0.0
 */
class PerformTranslationResponse {
    /**
     * Constructs a new <code>PerformTranslationResponse</code>.
     * @alias module:model/PerformTranslationResponse
     */
    constructor() { 
        
        PerformTranslationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PerformTranslationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PerformTranslationResponse} obj Optional instance to populate.
     * @return {module:model/PerformTranslationResponse} The populated <code>PerformTranslationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PerformTranslationResponse();

            if (data.hasOwnProperty('translation_job_ids')) {
                obj['translation_job_ids'] = ApiClient.convertToType(data['translation_job_ids'], ['String']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} translation_job_ids
 */
PerformTranslationResponse.prototype['translation_job_ids'] = undefined;

/**
 * @member {String} message
 */
PerformTranslationResponse.prototype['message'] = undefined;






export default PerformTranslationResponse;

