/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cielo24);
  }
}(this, function(expect, Cielo24) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cielo24.NewJobBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewJobBody', function() {
    it('should create an instance of NewJobBody', function() {
      // uncomment below and update the code to test NewJobBody
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be.a(Cielo24.NewJobBody);
    });

    it('should have the property jobName (base name: "job_name")', function() {
      // uncomment below and update the code to test the property jobName
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property requestor (base name: "requestor")', function() {
      // uncomment below and update the code to test the property requestor
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property expectedSpeakers (base name: "expected_speakers")', function() {
      // uncomment below and update the code to test the property expectedSpeakers
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

    it('should have the property isDuplicate (base name: "is_duplicate")', function() {
      // uncomment below and update the code to test the property isDuplicate
      //var instance = new Cielo24.NewJobBody();
      //expect(instance).to.be();
    });

  });

}));
